name: mobile
description: ENI project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  go_router: ^8.0.0
  getwidget: ^2.0.4

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.2.19
  form_validator: ^2.1.1
  flutter_spinkit: ^5.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  twilio_flutter: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  image_path_android: "android/app/src/main/res/mipmap"


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/sekoly.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/